// © 2026 AndrexTheDev – All Rights Reserved. See LICENSE.md.
import coreWebVitals from 'eslint-config-next/core-web-vitals';
import typescriptConfig from 'eslint-config-next/typescript';

/**
 * ESLint 9 flat config (eslint-config-next 16 is not compatible with ESLint 10 yet).
 * `next lint` was removed in Next.js 16, so the config lives here and is run
 * via `npm run lint`. `eslint-config-next` ships ready-made flat arrays.
 */
const config = [
  {
    ignores: [
      '.next/**',
      '.open-next/**',
      '.wrangler/**',
      'node_modules/**',
      'next-env.d.ts',
      'cloudflare-env.d.ts',
      'messages/**',
      // generated by scripts/run-harness.mjs
      '.tmp-smoke/**',
    ],
  },
  ...coreWebVitals,
  ...typescriptConfig,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'warn',
      'react/no-unescaped-entities': 'off',
    },
  },
  {
    // Tailwind + PostCSS configs are CommonJS by design (Tailwind v3 loads them
    // with its own CJS resolver), so `require()` is correct there.
    files: ['tailwind.config.js', 'postcss.config.mjs'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
];

export default config;
